---
title: "resume"
---

## Basic information

Name: Zhiwei Xin <br>
Date of birth: September 4th, 1999 <br>
Email: zhiweixin1@gmail.com <br>
Educational background: Master <br>
Tel: 3124512076 <br>


## Educational background

North China University of Technology - Computer Science and Technology <br>
Main courses:
Special Topic of C Language Programming (99), C++Language Programming (96), Wechat Applet Development (94), Data Structure (90), Digital Image Processing (92), MySQL Database Application (90), WeChat Applet Development, Web Design and Production, Software Testing, Computer Networks Basis and Application, Photoshop Topic <br>
Graduation design:
College Student Dormitory Management System Based on Springboot+Vue <br>

## Personal experience

Internship experience - Kingsoft Network - Technology Company - Server Operations Develop Engineer <br>
1. Maintaining operation of cloud platform service <br>
2. Handling faults of cloud platform and customer cloud host <br>
3. Maintaining operation of all components of the OpenStack cloud platform Carrying out daily inspection of the service running <br>
4. status of the host node where each resource pool is located <br>
5. Changing and upgrading the resource pool <br>
6. Compiling operation and maintenance automation scripts <br>

## Professional skills

Professional skills: Familiar with c/c++ language programming, data structure (c language), Html, Vue, PS, Spring boot, MySQL, SQL server, Java, Python <br>
Language skills: English CET-4, with good oral English expression ability <br>

## Projects

Application of Cloud Computing in the Internet of Things: Explored cloud computing applications in IoT, focusing on enhancing connectivity and data processing. <br>
College Student Dormitory Management System Based on Springboot+Vue: Developed a comprehensive dormitory management system, showcasing skills in web development and database management.